<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="F_CtoF" Id="{d3017ad7-e8df-4ce9-be86-335e073c1cc9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_CtoF : LREAL
VAR_INPUT
	lrTempInC : LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_CtoF := lrTempInC * (9.0/5.0) + 32.0;]]></ST>
    </Implementation>
    <LineIds Name="F_CtoF">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>